### ISSUE TITLE
[1.3.1] ROWREPEAT doesn't work when n=1

### ISSUE THREAD

**Issue by bdno86** [rxcle/rxindi#10]
# Problem

It seems that ROWREPEAT only works if the number of elements of any path is larger than one. 

This is not desirable behavior, as there are many scenarios in which it is unknown ahead of time whether an array will consist of just one element or more. 

In my particular case this happens when generating reports that have a contacts table. Some reports have one contact, others have multiple.

# Background

This is my setup:

<img width="1145" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/68248193-edc4-4390-9c07-83d5250f8213">

# N > 1 functions properly
With the following XML

```xml
<tenant>
        <name>Acme Inc.</name>
        <people>
            <name>Test Person 1</name>
            <position>CEO</position>
        </people>
        <people>
            <name>Test Person 2</name>
            <position>CTO</position>
        </people>
</tenant>
```

Everything works as expected:

<img width="1126" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/c5ef85a1-d0cb-4c5a-b438-175b7bf81abd">

# N = 1 Fails

The expected functionality fails however if the following XML is used:

```xml
<tenant>
        <name>Acme Inc.</name>
        <people>
            <name>Test Person 1</name>
            <position>CEO</position>
        </people>
</tenant>
```

Leading to the following output:

<img width="1150" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/95146362-549c-48f0-a81e-223e8b7bedbf">

**Comment by rxcle** [comment]
Ah yes, this was also observed in #5 which was marked as a bug initially. The fundamental issue here is that both LOOP and ROWREPEAT expect that the the path used points to a "container" element which holds the same "kind" of child elements. In your example it would work correctly if all `people` elements would be in a containing `peoples` element and the path is changed to `/tenant/peoples`

As also remarked in #5 the documentation is not clear about this at all and the behavior can leave users confused (rightfully so), also and in particular cases one might not even want this behavior (i.e.: here is some whatever XPath, just iterated over its result). What's worse: some XML structures are not really well supported by this limitation - which kind of goes against one of the fundamental "total freedom" principles of rxindi... so yeah something needs to be done. It is on the ambition list for the next minor release.

The only (known) workaround right now is to either changes the source XML or if that is not possible/desirable, in the template to add an IF-ELSE statement around the table that checks for the "only 1" condition and handle that case explicitly...

**Comment by bdno86** [comment]
Aah I see. Quite unfortunate but no man overboard given that there is a workaround.

I'm already converting json to XML to work with Rxindi seperately (the builtin json -> xml conversion tool doesn't seem to work for me), but I think I'll make some changes on our backend to change the out put from

```json
"tenant": {
    "name": "Acme",
    "people": [
        {
            "name": "Person 1",
            "position": "CEO"
        }
    ]
},
```

to

```json
"tenant": {
    "name": "Acme Inc.",
    "people": [
        {
            "person": {
                "name": "Person 1",
                "position": "CEO"
            }
        }
    ]
},
```

What really tripped me up is that json has the concept of n=1 arrays or even empty arrays, which turns out is hard to represent in XML.

Thanks for the quick response and explanation!

**Comment by rxcle** [comment]
You can use the XPath `count` function for that: 
```
${?count(people)=1}One${:}${?count(people)=0}Zero${:}More than one${.}${.}
```

It is interesting that you mention that the JSON conversion doesn't work. Do you mean it physically doesn't work or it produces an undesired result? Could you provide some more detail on this, so this can be investigated?

**Comment by bdno86** [comment]
That is super helpful. I must have missed that XPath functions can be run inside of Rxindi tags. This solves just about the entire problem. Thanks!

**Comment by rxcle** [comment]
Good to hear. And thank you for bringing some real-life issues on working with Rxindi to our attention. 
We'll close this one for now and keep track on improvements in this area under #5.
