### ISSUE TITLE
[1.3.1] Add Action types for changing table/row/cell styles

### ISSUE THREAD

**Issue by rxcle** [rxcle/rxindi#13]
The ACTION statement has action types for setting Object, Character and Paragraph styles. Which, if used in combination with IF allows for dynamic styling of a document, based on input data. To allow for dynamic styling of InDesign tables in a similar fashion, consider adding new ACTION types for changing the current style of a Table, Row and Cell.

## Arguments for
- More dynamic styling options
- Allowing dynamic styling of tables will enable some great on-the fly formatting options
- Should be relatively low effort to add, with little perceived risk of breaking existing functionality and low impact on testing

## Arguments against
- Unknown

**Comment by bdno86** [comment]
I was going to add a request for this haha. I now do it in this clunky way, but a way to conditionally set row or cell styling would be amazing. 
<img width="999" alt="image" src="https://github.com/rxcle/rxindi/assets/1181888/37e53825-231d-4414-9501-57a31640ac90">
