### ISSUE TITLE
Problème Rwindi sur mac

### ISSUE THREAD

**Issue by palissade** [rxcle/rxindi#2]
Bonjour
Je viens d'acheter l'extension Rxindi pour indesign 2022. et cela ne fonctionne pas.Il affiche "validating..."
et rien de se passe. 
idem avec "processing..." et rien.
Je viens de voir qu'il fonctionne sur mon pc. Sauf que je ne travaille pas sur PC.
<img width="1170" alt="Capture d’écran 2022-04-07 à 11 18 13" src="https://user-images.githubusercontent.com/20424083/162165954-4a9f3671-b80e-47f2-9ec0-f061cdeb6483.png">

**Comment by rxcle** [comment]
I am sorry to hear that the Rxindi does not work on your Mac. Rxindi was originally released for Intel-based Macs and has not had an update for newer Apple Silicon Mac (M1 chips) support yet. This is being worked on but at this time we cannot give a timeframe for an updated release. I don't think this fact is mentioned on the Adobe marketplace, we will address that as soon as possible so not to disappoint more people after already having made the purchase.
The update with Apple Silicon support will be a free one for people who already have purchased a license previously.

**Comment by rxcle** [comment]
Version 1.1.0 has just been released with official Apple Silicon support.
https://github.com/rxcle/rxindi/releases/tag/v1.1.0
